spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/teamwork_db?serverTimezone=UTC&useSSL=false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
